
public enum EVENT_TYPES
{
    LABEL = -1,
    MOVEMNET,
    DIALOGUE,
    SET_HEALTH,
    RUN_CHARACTER_SCRIPT,
    ANIMATION,
    SOUND,
    GO_TO_SCENE,
    SET_FLAG,
    CHECK_FLAG,
    CAMERA_MOVEMENT,
    BREAK_EVENT,
    CHANGE_CAM_COLOUR,
    UTILITY_FOCUS,
    FADE,
    OBJECT,
    DISPLAY_CHARACTER_HEALTH,
    UTILITY_INITIALIZE,
    UTILITY_CHECK,
    WAIT,
    CHOICE,
    PUT_SHUTTERS,
    ADD_INVENTORY,
    TELEPORT,
    SHOW_TEXT,
    CHANGE_MAP,
    DISPLAY_ICON,
    SET_UTILITY_FLAG
}
public enum LOGIC_TYPE
{
    VAR_GREATER,
    VAR_EQUAL,
    VAR_LESS,
    ITEM_OWNED,
    CHECK_UTILITY_RETURN_NUM,
    CHECK_CHARACTER,
    CHECK_CHARACTER_NOT
}